vars:
  - methods : ['anydoor','catdm', 'stableviton']

stages:

  compute_lpips:
    foreach: ${methods}
    do:
      cmd: poetry run python src/scripts/compute_lpips.py -d0 data/vton_gt -d1 data/vton_${item} -o data/metrics_${item}/LPIPS_${item}.txt
      deps:
        - data/vton_gt
        - data/vton_${item}
      outs:
        - data/metrics_${item}/LPIPS_${item}_all.txt
        - data/metrics_${item}/LPIPS_${item}.txt

  compute_fid:
    foreach: ${methods}
    do:
      cmd: python -m pytorch_fid data/vton_gt data/vton_${item} | grep 'FID:' | awk '{print $2}' > data/metrics_${item}/FID_${item}.txt
      deps:
        - data/vton_gt
        - data/vton_${item}
      outs:
        - data/metrics_${item}/FID_${item}.txt

  compute_ssim:
    foreach: ${methods}
    do:
      cmd: poetry run python src/scripts/compute_ssim.py -d0 data/vton_gt -d1 data/vton_${item} -o data/metrics_${item}/SSIM_${item}.txt
      deps:
        - data/vton_gt
        - data/vton_${item}
      outs:
        - data/metrics_${item}/SSIM_${item}_all.txt 
        - data/metrics_${item}/SSIM_${item}.txt  
  

