stages:
  # dummy_image_generation:
  #   cmd: poetry run python -m src.scripts.dummy_generation_script --input-folder data/vton_subset/image --output-folder data/vton_subset_generation
  #   deps:
  #     - data/vton_subset/image
  #   outs:
  #     - data/vton_subset_generation
    
  compute_anydoor_lpips:
    cmd: poetry run python src/scripts/compute_lpips.py -d0 data/vton_gt -d1 data/vton_anydoor -o data/LPIPS_anydoor.txt
    deps:
      - data/vton_gt
      - data/vton_anydoor
    outs:
      - data/LPIPS_anydoor_all.txt
      - data/LPIPS_anydoor.txt

  compute_anydoor_fid:
    cmd: python -m pytorch_fid data/vton_gt data/vton_anydoor | grep 'FID:' | awk '{print $2}' > data/FID_anydoor.txt
    deps:
      - data/vton_gt
      - data/vton_anydoor
    outs:
      - data/FID_anydoor.txt

  compute_anydoor_ssim:
    cmd: poetry run python src/scripts/compute_ssim.py -d0 data/vton_gt -d1 data/vton_anydoor -o data/SSIM_anydoor.txt
    deps:
      - data/vton_gt
      - data/vton_anydoor
    outs:
      - data/SSIM_anydoor_all.txt 
      - data/SSIM_anydoor.txt  