vars:
  - methods : ['anydoor','catdm', 'stableviton']
  - loras : ['nolora', 'kenzo_lora', 'zara_lora']

stages:

  compute_lpips:
    foreach: ${methods}
    do:
      cmd: poetry run python -m src.scripts.compute_lpips -d0 data/vton_gt -d1 data/vton_${item} -o data/metrics_${item}/LPIPS_${item}.txt
      deps:
        - data/vton_gt
        - data/vton_${item}
      outs:
        - data/metrics_${item}/LPIPS_${item}_all.txt
        - data/metrics_${item}/LPIPS_${item}.txt

  compute_fid:
    foreach: ${methods}
    do:
      cmd: poetry run python -m pytorch_fid data/vton_gt data/vton_${item} | grep 'FID:' | awk '{print $2}' > data/metrics_${item}/FID_${item}.txt
      deps:
        - data/vton_gt
        - data/vton_${item}
      outs:
        - data/metrics_${item}/FID_${item}.txt

  compute_kid:
    foreach: ${methods}
    do:
      cmd: poetry run fidelity --kid --input1 data/vton_gt --input2 data/vton_${item}| grep 'kernel_inception_distance_mean\|kernel_inception_distance_std' > data/metrics_${item}/KID_${item}.txt
      deps:
        - data/vton_gt
        - data/vton_${item}
      outs:
        - data/metrics_${item}/KID_${item}.txt

  compute_ssim:
    foreach: ${methods}
    do:
      cmd: poetry run python -m src.scripts.compute_ssim -d0 data/vton_gt -d1 data/vton_${item} -o data/metrics_${item}/SSIM_${item}.txt
      deps:
        - data/vton_gt
        - data/vton_${item}
      outs:
        - data/metrics_${item}/SSIM_${item}_all.txt 
        - data/metrics_${item}/SSIM_${item}.txt  
  
  concat_images_for_comparison:
    cmd: poetry run python -m src.scripts.concat_images -c config/comparison.yaml -o data/comparison_images
    deps:
      - config/comparison.yaml
      - data/vton_gt
      - data/vton_anydoor
      - data/vton_catdm
      - data/vton_stableviton
    outs:
      - data/comparison_images




  compute_lpips_loras:
    foreach: ${loras}
    do:
      cmd: python -m src.scripts.compute_lpips -d0 data/adaptation_subset -d1 data/adaptation_${item} -o data/metrics_${item}/LPIPS_${item}.txt
      deps:
        - data/adaptation_subset
        - data/adaptation_${item}
      outs:
        - data/metrics_${item}/LPIPS_${item}_all.txt
        - data/metrics_${item}/LPIPS_${item}.txt

  compute_fid_loras:
    foreach: ${loras}
    do:
      cmd: python -m pytorch_fid data/adaptation_subset data/adaptation_${item} | grep 'FID:' | awk '{print $2}' > data/metrics_${item}/FID_${item}.txt
      deps:
        - data/adaptation_subset
        - data/adaptation_${item}
      outs:
        - data/metrics_${item}/FID_${item}.txt

  compute_kid_loras:
    foreach: ${loras}
    do:
      cmd: fidelity --kid --input1 data/adaptation_subset --input2 data/adaptation_${item}| grep 'kernel_inception_distance_mean\|kernel_inception_distance_std' > data/metrics_${item}/KID_${item}.txt
      deps:
        - data/adaptation_subset
        - data/adaptation_${item}
      outs:
        - data/metrics_${item}/KID_${item}.txt

  compute_ssim_loras:
    foreach: ${loras}
    do:
      cmd: python -m src.scripts.compute_ssim -d0 data/adaptation_subset -d1 data/adaptation_${item} -o data/metrics_${item}/SSIM_${item}.txt
      deps:
        - data/adaptation_subset
        - data/adaptation_${item}
      outs:
        - data/metrics_${item}/SSIM_${item}_all.txt 
        - data/metrics_${item}/SSIM_${item}.txt  