[project]
name = "object-insertion"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Daniel Rodriguez", email = "darc2203@gmail.com" }
]
dependencies = [
    "pyyaml>=6.0.2",
    "dvc-s3>=3.2.0",
    "tqdm>=4.67.1",
    "pytorch-fid>=0.3.0",
    "scikit-image>=0.24.0",
    "pillow>=11.0.0",
    "omegaconf>=2.3.0",
    "torch-fidelity>=0.3.0",
    "lpips>=0.1.4",
    "opencv-python>=4.10.0.84",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/object_insertion"]
