"""Postprocessing script to concatenate images generated by all models."""

import argparse
import os

import cv2
import numpy as np
from omegaconf import DictConfig, OmegaConf
from tqdm import tqdm

from src.utils import resize_images


def concat_images(config: DictConfig, output_folder: str) -> None:
    """Concatenate images generated by different models."""
    # Create the output folder if it does not exist
    os.makedirs(output_folder, exist_ok=True)

    # Iterate over the image filenames
    for image_filename in tqdm(config.selected_images):
        # Load the images from the different models
        images = {}
        for name, path in config.folders.items():
            image_path = os.path.join(path, image_filename)
            image = cv2.imread(image_path)
            images[name] = image

        # Resize the images to the common size
        images = resize_images(images)
        images_values = list(images.values())
        # Concatenate the images horizontally
        concatenated_image = np.concatenate(images_values, axis=1)
        # Save the concatenated image
        output_path = os.path.join(output_folder, image_filename)
        cv2.imwrite(output_path, concatenated_image)


def main():
    """Main function to parse arguments and process images."""
    # Set up the argument parser
    parser = argparse.ArgumentParser(description="Concatenate images.")
    parser.add_argument(
        "-c", "--config", type=str, help="Path to the yaml configuration file."
    )
    parser.add_argument(
        "-o",
        "--output-folder",
        type=str,
        help="Path to the output folder where concatenated images will be saved.",
    )

    args = parser.parse_args()
    config = DictConfig(OmegaConf.load(args.config))

    # Process images with the specified parameters
    concat_images(config, args.output_folder)


if __name__ == "__main__":
    main()
